### ISSUE TITLE
Integrate CSS from Bill's work

### ISSUE THREAD

**Issue by jathayde** [meticulous/state-decoded-ui-2012#12]
https://github.com/statedecoded/statedecoded/pull/251

**Comment by lynnwallenstein** [comment]
Integrated: https://github.com/meticulous/state-decoded-ui-2012/commit/864c1d113105e000ee5ee8d7952f60c111c34a34 ... needs to be tested as I didn't have the markup, but all the CSS from that pull is in there.

**Comment by krusynth** [comment]
Feel free to change any of that, btw - I didn't have your designs to go on when I made it. :)
