### ISSUE TITLE
Test site in MSIE

### ISSUE THREAD

**Issue by jathayde** [meticulous/state-decoded-ui-2012#3]
Building standards compliant in class A browsers first, then will use browser stack to test for and debug MSIE issues

**Comment by jathayde** [comment]
Testing will be done in BrowserStack, an online Sass that lets you hit your localhost.

**Comment by jalbertbowden** [comment]
i'm not arguing your tactics, but i've always found native installs to be the only real way to test in ie. i have ie10, can roll back to ie8. how far back do you want to support?

**Comment by jathayde** [comment]
IE8. I use VMs for each instance and setup. The other things we use with great success are SauceLabs and Browser Stack

**Comment by krusynth** [comment]
@jalbertbowden Microsoft now provides VMs to test against for all major browser versions.  This tool is really fantastic to manage them:

https://github.com/xdissent/ievms
