### ISSUE TITLE
Github type display for keyboard shortcuts

### ISSUE THREAD

**Issue by lynnwallenstein** [meticulous/state-decoded-ui-2012#6]
A modal is implemented on the index.html with the keyboard shortcut of "?".

That is the only shortcut made currently and there is no help yet, but it is using:

http://craig.is/killing/mice

and 

http://twitter.github.com/bootstrap/javascript.html#modals

**Comment by lynnwallenstein** [comment]
Pushing to John for review

**Comment by waldoj** [comment]
I'm on the go, so don't have details now, but note that a pattern for this has been implemented already, just in the past week, and it's really similar. Will post a link later.

**Comment by jathayde** [comment]
We'll balance with this https://github.com/statedecoded/statedecoded/pull/252

**Comment by waldoj** [comment]
Thanks for finding the thing I was referring to, John. :)
